### ISSUE TITLE
issue when writing file

### ISSUE THREAD

**Issue by irfansyedsasken** [jprichardson/node-jsonfile#100]
Uncaught (in promise) TypeError: fs.readFile is not a function
    at Object.readFile (http://localhost:3000/static/js/bundle.js:60555:7)
    at DashBoard._callee3$ (http://localhost:3000/static/js/bundle.js:58450:25)
    at tryCatch (http://localhost:3000/static/js/bundle.js:59315:41)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:59553:23)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:59367:22)
    at step (http://localhost:3000/static/js/bundle.js:58299:192)
    at http://localhost:3000/static/js/bundle.js:58299:362
    at <anonymous>

**Comment by RyanZim** [comment]
@irfansyedsasken Are you trying to use `jsonfile` in a browser?

**Comment by irfansyedsasken** [comment]
@RyanZim  yes using react js

**Comment by RyanZim** [comment]
This is a module for use in Node.js, not the browser. That's why you're getting this error.
