### ISSUE TITLE
does this really not handle circular objects?

### ISSUE THREAD

**Issue by haemse** [jprichardson/node-jsonfile#112]
`TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/home/pi/cerebrum_domum/node_modules/jsonfile/index.js:89:20)
    at Object.writeFileWithCallback (/home/pi/cerebrum_domum/node_modules/jsonfile/index.js:104:11)
    at Object.writeFileWithCallback [as writeFile] (/home/pi/cerebrum_domum/node_modules/universalify/index.js:5:67)
    at storeSettings (/home/pi/cerebrum_domum/init_cortex_cerebri.js:104:14)
    at Timeout.setTimeout [as _onTimeout] (/home/pi/cerebrum_domum/init_cortex_cerebri.js:111:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
`

**Comment by RyanZim** [comment]
Yes, that's correct; `JSON.stringify()` itself doesn't support circular objects.
