### ISSUE TITLE
[bug] functions readFile and writeFile execute callbacks even if there are errors/missing args (not matching fs behaviour)

### ISSUE THREAD

**Issue by emarteca** [jprichardson/node-jsonfile#145]
Hi all! I'm working on an automated test generator and have been testing it by applying regression testing to a set of popular npm libraries, including yours! In [this commit](https://github.com/jprichardson/node-jsonfile/commit/e3d86e09e567992bca6b963fe181364cd3b095b4) I found a difference in the behaviour of `readFile` and `writeFile` when called with incorrect arguments. 

### The issue
Functions that have been converted with `universalify.fromPromise` execute the callback argument even when the other arguments are missing or invalid. It looks like this results in a bug, because the comparable `fs` functions do error checking of these arguments.

#### To replicate the issue:
```
let jsonfile = require('jsonfile'');
function callback() { 
  console.log("Callback executing!");
  console.log(arguments);
}
jsonfile.readFile("existingFile.js", callback); // correct call
jsonfile.readFile( callback); // incorrect call
```
Before the change in [this commit](https://github.com/jprichardson/node-jsonfile/commit/e3d86e09e567992bca6b963fe181364cd3b095b4),  the output of running the above code is:
```
// correct call output: 
> Callback executing!
> [Arguments] { '0': null, '1': 'file contents' }
// incorrect call output:
> Uncaught:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received function callback
    at readFile (fs.js:326:10)
...
```
Then, after the update, the output of running the above code is:
```
// correct call output:
> Callback executing!
> [Arguments] { '0': null, '1': 'file contents' }
// incorrect call output:
> Callback executing!
> [Arguments] {                                                                                                                                                                
  '0': TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined                                        
      at readFile (fs.js:326:10)  
...
```
So, the callback is now executed even when the arguments are incorrect, and have the function error passed in as an argument to the callback.

### What is causing this behaviour
[This change](https://github.com/jprichardson/node-jsonfile/commit/e3d86e09e567992bca6b963fe181364cd3b095b4#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R38) from using  the [universalify](https://www.npmjs.com/package/universalify) library’s `fromPromise` function instead of `fromCallback` is causing the difference.

Looking at [the implementation of `fromPromise`](https://github.com/RyanZim/universalify/blob/master/index.js#L18): this function takes a function `fn` as an argument, and returns a new function that
* calls `fn` as it would normally be called, [if the last argument is not a callback](https://github.com/RyanZim/universalify/blob/master/index.js#L21)
* [if the last argument _is_ a callback](https://github.com/RyanZim/universalify/blob/master/index.js#L22), then `fn` is called with all but its last argument (this is `fn.apply(this, args.slice(0, -1))`). As [stated in the documentation](https://github.com/RyanZim/universalify#universalifyfrompromisefn), the `fromPromise` function assumes that `fn` returns a promise.  Then, it chains a `.then` to the return of the call, passing the function `r => cb(null, r)` as the resolve of this `.then` promise, and `cb` (the callback argument itself) as the reject function.

In our case, we see that the incorrect call to `readFile` does result in an error `TypeError[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL.`. And so, the promise resulting from the call to `readFile` is rejected. As such, the reject branch of the `.then` is triggered, which results in our callback being executed. 

We see that in our callback, the `TypeError` is printed as it is the argument to the callback.

#### `writeFile`: another function with this behaviour
The [`writeFile` function is also universalified with `fromPromise`](https://github.com/jprichardson/node-jsonfile/commit/e3d86e09e567992bca6b963fe181364cd3b095b4#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R71). As such, calling `writeFile` with only a callback has the same behaviour as `readFile` (i.e. the callback is executed).
```
jsonfile.writeFile("file.json","output string", callback); // correct call
> Callback executing!
> [Arguments] { '0': null }

// incorrect call still executes the callback
jsonfile.writeFile( callback); 
> Callback executing!
>  [Arguments] {                                                                                                                                                                
  '0': TypeError: Cannot read property 'replace' of undefined                                                                                                                  
      at stringify
...
```

### Comparison to behaviour of corresponding 'fs' functions
I assume `writeFile` and `readFile` should have similar error checking to `fs.writeFile` and `fs.readFile` respectively; both of these functions have a type error if you try and call them with just a callback.
```
let fs = require('fs');
fs.writeFile(callback); // this function expects 3 arguments, and the last must be a callback
> Uncaught:                                                                                                                                                                            
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined                                                                                                    
    at maybeCallback (fs.js:160:9)
    at Object.writeFile (fs.js:1431:14)

fs.readFile(callback);
Uncaught:
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:160:9)
    at Object.readFile (fs.js:311:14)
...
```

### Fix 
It is not enough to just add argument type checking code to the implementations of `readFile` and `writeFile`: because of the design of `fromPromise`, the callback will be executed regardless of the contents of these functions.
I have a proposed fix that simply involves replicating the implementation of `fromPromise` in the body of these functions, after some type checking. 
I'll make a PR soon!

**Comment by emarteca** [comment]
Relevant PR: #146

**Comment by RyanZim** [comment]
Closing as this seems to be an edge case few people care about.
