### ISSUE TITLE
Failed to read application data TypeError: content.replace is not a function

### ISSUE THREAD

**Issue by kuy** [jprichardson/node-jsonfile#50]
I got an error with my setup (Webpack + Babel + Electron). Here is a full backtrace.

```
Failed to read application data TypeError: content.replace is not a function
    at stripBom (/Users/kodama/Work/fika-electron/dist/main.bundle.js:229:22)
    at Object.readFileSync (/Users/kodama/Work/fika-electron/dist/main.bundle.js:175:14)
    at Object.<anonymous> (/Users/kodama/Work/fika-electron/dist/main.bundle.js:84:32)
    at __webpack_require__ (/Users/kodama/Work/fika-electron/dist/main.bundle.js:20:30)
    at /Users/kodama/Work/fika-electron/dist/main.bundle.js:40:18
    at Object.<anonymous> (/Users/kodama/Work/fika-electron/dist/main.bundle.js:43:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

In the process of debugging node-jsonfile module, I figured out the error is raised at following line ([sourcecode](https://github.com/jprichardson/node-jsonfile/blob/master/index.js#L115)).

``` js
function stripBom (content) {
  // we do this because JSON.parse would convert it to a utf8 string if encoding wasn't specified
  if (Buffer.isBuffer(content)) content = content.toString('utf8') // THIS LINE
  content = content.replace(/^\uFEFF/, '')
  return content
}
```

In the line, `Buffer.isBuffer(...)` returns `false` even if `content` is `Buffer` instance.  Because `Buffer.isBuffer(...)` API relies on `instanceof` operator for checking type ([sourcecode](https://github.com/nodejs/node/blob/master/lib/buffer.js#L307-L309)), we can use `typeof` operator for increasing robustness and workaround.

``` js
if (typeof content !== 'string') content = content.toString('utf8')
```

By the way, when I run a code without Webpack and Babel, it works well. I couldn't determine which layer causes this issue.

Is there anyone struggling same issue?

**Comment by RyanZim** [comment]
@kuy Is this still an issue with the latest version of jsonfile and node.js?

**Comment by RyanZim** [comment]
Closing for lack of response.
